# Generated by Django 5.1 on 2024-08-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professor",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
            },
        ),
        migrations.AddField(
            model_name="professor",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("Graduação", "Graduação"),
                    ("Pós-Graduação", "Pós-Graduação"),
                    ("Mestrado", "Mestrado"),
                    ("Doutorado", "Doutorado"),
                ],
                default="Graduação",
                max_length=50,
                null=True,
                verbose_name="Nível",
            ),
        ),
    ]
