# Generated by Django 5.1 on 2024-08-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professor", "0003_alter_professor_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="data_nascimento",
            field=models.DateField(null=True, verbose_name="Data de Nascimento"),
        ),
    ]
