# Generated by Django 5.1 on 2024-08-14 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("professor", "0002_alter_professor_options_professor_nivel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nome_completo",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Nome Completo"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(null=True, verbose_name="Data de nascimento"),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Endereço"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        verbose_name="Telefone do aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aluno(a)",
                "verbose_name_plural": "Alunos",
                "ordering": ["turma", "nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome/Identificação da turma.",
                        max_length=255,
                        null=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "ano",
                    models.IntegerField(
                        help_text="Ano da turma Ex.: 2024", verbose_name="Ano"
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        help_text="Professor responável pela turma.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="professor.professor",
                        verbose_name="Professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": ("Turmas",),
                "ordering": ["ano"],
            },
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "disciplina",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Disciplina"
                    ),
                ),
                ("valor_nota", models.FloatField(verbose_name="Valor da Nota")),
                (
                    "data_lancamento",
                    models.DateField(verbose_name="Data de lançamento"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turma.aluno",
                        verbose_name="Aluno(a)",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turma.turma",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
                "ordering": ["data_lancamento", "aluno", "disciplina"],
            },
        ),
        migrations.AddField(
            model_name="aluno",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="turma.turma",
                verbose_name="Turma",
            ),
        ),
    ]
