# Generated by Django 5.1 on 2024-08-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disciplina", "0001_initial"),
        ("professor", "0003_alter_professor_user"),
        ("turma", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="turma",
            options={
                "ordering": ["ano"],
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
            },
        ),
        migrations.AlterField(
            model_name="aluno",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos",
                to="turma.turma",
                verbose_name="Turma",
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas",
                to="turma.aluno",
                verbose_name="Aluno(a)",
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="disciplina",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="disciplina.disciplina",
                verbose_name="Disciplina",
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas",
                to="turma.turma",
                verbose_name="Turma",
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="professor",
            field=models.ForeignKey(
                help_text="Professor responável pela turma.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turmas",
                to="professor.professor",
                verbose_name="Professor",
            ),
        ),
    ]
