# Generated by Django 5.1 on 2024-08-14 19:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("disciplina", "0001_initial"),
        ("turma", "0002_alter_turma_options_alter_aluno_turma_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("Segunda", "Segunda"),
                            ("Terça", "Terça"),
                            ("Quarta", "Quarta"),
                            ("Quinta", "Quinta"),
                            ("Sexta", "Sexta"),
                            ("Sábado", "Sábado"),
                        ],
                        max_length=9,
                        verbose_name="Dia da semana",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="Hora de início")),
                ("hora_fim", models.TimeField(verbose_name="Hora de término")),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="disciplina.disciplina",
                        verbose_name="Disciplina",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="turma.turma",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário",
                "verbose_name_plural": "Horários",
                "ordering": ["dia_semana", "hora_inicio"],
            },
        ),
    ]
